name: system_resources
description: Provides easy access to system resources (CPU load, memory usage).
version: 1.0.0
homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.9.0
